_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 100
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 100
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.14
            "5": 0.18.6
            "6": 4.45.2
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
